# Generated by Django 6.0.6 on 2026-06-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CHECKIN', 'Check In'), ('CHECKOUT', 'Check Out'), ('CANCEL', 'Cancel')], max_length=20)),
                ('record_type', models.CharField(max_length=50)),
                ('record_id', models.PositiveIntegerField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[('IB', 'Inbound'), ('OB', 'Outbound'), ('Both', 'Both')], default='Both', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Occupied', 'Occupied'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['door_name'],
            },
        ),
        migrations.CreateModel(
            name='PITOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CapacityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_slot', models.TimeField()),
                ('appt_type', models.CharField(choices=[('IB', 'Inbound'), ('OB', 'Outbound'), ('Both', 'Both')], default='Both', max_length=10)),
                ('max_appointments', models.PositiveSmallIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('month', 'day_of_week', 'time_slot', 'appt_type')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_type', models.CharField(choices=[('IB', 'Inbound'), ('OB', 'Outbound')], max_length=2)),
                ('appt_date', models.DateField()),
                ('appt_time', models.TimeField()),
                ('scheduled_datetime', models.DateTimeField()),
                ('bol_shipment_no', models.CharField(blank=True, max_length=100)),
                ('delivery_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Checked In', 'Checked In'), ('Completed', 'Completed'), ('Late', 'Late'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carrier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producttype')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DriverVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('trailer_no', models.CharField(blank=True, max_length=100)),
                ('drivers_license_state', models.CharField(blank=True, max_length=50)),
                ('load_lock', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'N/A')], max_length=2)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('dwell_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('in_out_status', models.CharField(blank=True, choices=[('In', 'In'), ('Out', 'Out')], max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='core.appointment')),
                ('assigned_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.door')),
                ('pit_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pitoperator')),
            ],
        ),
    ]
